# Generated by Django 4.1.1 on 2022-09-28 01:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='fk_supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='profiles.supplier'),
        ),
    ]
