# Generated by Django 4.1.1 on 2022-09-24 01:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_sell', models.IntegerField()),
                ('total_price', models.DecimalField(decimal_places=10, max_digits=19)),
                ('fk_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.category')),
                ('fk_client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='user.client')),
                ('fk_product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.product')),
            ],
        ),
    ]
